name: Publish Package

on:
  push:
    branches:
      - main  # or the branch you want to trigger this workflow

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust based on your project's requirements

    - name: Install dependencies
      run: npm install

    - name: Bump version and publish
      run: |
        npm install -g standard-version
        standard-version --release-as patch
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "chore(release): bump version to $(node -p "require('./package.json').version")"
        git tag -a "v$(node -p "require('./package.json').version")" -m "Release version $(node -p "require('./package.json').version")"
        git push origin main --tags
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
